### ISSUE TITLE
Rework Wafflebot automatization

### ISSUE THREAD

**Issue by maxhbr** [fossology/fossology#1163] opened 2018-08-16 13:59 UTC
The current waffle bot automatization looks like:
![2018-08-16_15 53 06](https://user-images.githubusercontent.com/1187050/44212848-bc26cf00-a16c-11e8-93eb-bde628bbf541.png)
I would propose to change it to:
![2018-08-16_15 53 55](https://user-images.githubusercontent.com/1187050/44212857-c2b54680-a16c-11e8-8f7b-95b5ff6b5557.png)
for multiple reasons:
- the `needs code review` label is not the correct for marking the `needs review` column. If one starts reviewing he would move it to `in review` and drop the `needs code review` label despite only maybe doing testing
- the wafflebot never adds the `needs test` label
- on every push to a branch the wafflebot removes the potentially existing `WIP` label and replaces it by a `needs code review` label
  - this might lead to an anoing fight:
![2018-08-13_08 59 50](https://user-images.githubusercontent.com/1187050/44213128-4d964100-a16d-11e8-8e58-37a545751445.png)

**Comment by GMishx** [comment] 2018-08-17 03:48
Do we need Waffle? Like Github also provides us insights in the [pulse tab](https://github.com/fossology/fossology/pulse/monthly) like open PRs, merged PRs, issues, etc.

**Comment by maxhbr** [comment] 2018-08-17 22:49
I think the waffle.io board is used by some developers

**Comment by GMishx** [comment] 2022-01-27 15:56
waffle.io is shutdown. The issue is no longer valid.

**Closed by GMishx** 2022-01-27 15:56 UTC
Labels: org
