### ISSUE TITLE
add migration testing into CI system 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#256] opened 2015-01-09 06:00 UTC
---

Author Name: **larry shi** 
Original Redmine Issue: 6303, http://www.fossology.org/issues/6303
Original Date: 2014/01/07
Original Assignee: larry shi

---

form me, one Debian-like and one RHEL-like distribution are enough.

**Comment by mcjaeger** [comment] 2015-08-28 18:49
can we close it?

**Comment by bobgob** [comment] 2015-08-28 21:25
we only have manual migration testing.  The issue is to put this into the CI system but I think that is going to be difficult with travis and we will have to use the LF infrastructure.

**Comment by mcjaeger** [comment] 2015-11-19 16:13
again, we need the package build anyways before.

**Comment by mcjaeger** [comment] 2018-05-28 10:53
there is not official CI

**Closed by mcjaeger** 2018-05-28 10:53 UTC
Labels: Category: Testing, bug
