### ISSUE TITLE
Standalone nomos messes up output in -d mode

### ISSUE THREAD

**Issue by AMDmi3** [fossology/fossology#753] opened 2017-03-02 14:22 UTC
I'm using standalone nomos scanner to extract license information from a specific set of sources. I run:

```
nomossa -l -d . | cat -n
```

Is I understand, this way nomos spawns a child process, but it seems like data from it is not processed by master correctly, which results in damaged output:

```
    72	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/tests/test_pointrect.cc contains license(s) No_license_found
    73	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/tests/test_optional.cc contains license(s) No_license_found
    74	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/tests/test_error.cc contains license(s) No_license_found
    75	File /usr/work/usr/ports/devel/sdl2pp/lib
    76	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/mixer.cc contains license(s) Zlib
    77	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/lines.cc contains license(s) Zlib
    78	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/mixer_effects.cc contains license(s) Zlib
    79	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/sprites.cc contains license(s) Zlib
    80	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/ttf.cc contains license(s) Zlib
    81	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/mixer_music.cc contains license(s) Zlib
    82	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/CHANGES.md contains license(s) No_license_found
    83	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/exttests/cmake/CMakeLists.txt contains license(s) No_license_found
    84	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/FindSDL2PP.cmake.in contains license(s) No_license_found
    85	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/testdata/README.md contains license(s) See-file
    86	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/testdata/crate.png contains license(s) No_license_found
    87	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/testdata/test.wav contains license(s) No_license_found
    88	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/testdata/test.ogg contains license(s) No_license_found
    89	work/libSDL2pp-0.13.0/.travis.yml contains license(s) No_license_found
    90	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/audio_wav.cc contains license(s) Zlib
    91	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/image.cc contains license(s) Zlib
    92	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/audio_sine.cc contains license(s) Zlib
    93	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/CMakeLists.txt contains license(s) No_license_found
    94	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/rendertarget.cc contains license(s) Zlib
    95	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/examples/mixer_music_sine.cc contains license(s) Zlib
    96	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/.appveyor.yml contains license(s) No_license_found
    97	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/sdl2pp.pc.in contains license(s) No_license_found
    98	File /usr/work/usr/ports/devel/sdl2pp/work/libSDL2pp-0.13.0/exttests/pkg-config/Makefile contains license(s) No_license_found
```

**Comment by AMDmi3** [comment] 2017-03-03 09:27
Update: there's ```-n``` switch which allows to set a number of child processes. It cannot be set lower than 2, with doc saing "parent process and one child process", but that is not correct as this is actually a number of child processes. If source is fixed and ```-n``` is allowed to be set to 1, output is no more garbled. But obviously that results in single-thread scan.

**Comment by mcjaeger** [comment] 2017-03-07 21:55
I am not sure if that is a bug or an enhancement. I am not using Nomos as standalone at all, but from what I understand it is a natural result form the parallelization of scanning. What could be done is to join all results at the end of the scanning and sort then the output before printing. Is it that what you anticipate?

**Comment by fogninid** [comment] 2017-03-08 15:56
The -d option does not work correctly and should be removed: external parallelization is easier than fixing it.

This is a duplicate of #396.

**Closed by fogninid** 2017-03-08 15:56 UTC
