### ISSUE TITLE
Commenting uses/contributions/process descriptions 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#100] opened 2015-01-08 07:04 UTC
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2409, http://www.fossology.org/issues/2409
Original Date: 2012/06/15

---

None

**Comment by steffen-weber** [comment] 2015-12-21 20:27
duplicate of #22

**Closed by steffen-weber** 2015-12-21 20:27 UTC
Labels: Priority: Normal, Status: New, Tracker: Documentation
