### ISSUE TITLE
allow anonymous user to browse (mod=browse)

### ISSUE THREAD

**Issue by mhow2** [fossology/fossology#994] opened 2018-03-05 12:13 UTC
Is it possible ? I can't find my way to the setting that would allow that. I'm using the latest Docker release.

My goal is to allow the default "Software repository" folder to be readable for everyone, even non logged-in users...

Instead I get the following:

![screenshot-2018-3-5 browse](https://user-images.githubusercontent.com/9987241/36974576-68e8731e-2077-11e8-9825-4aebb3ed677f.png)

There is this "Processing..." notice that is freezed
In the web dev pane I see:

```
12:28:20,219 default DEBUG executing
'FossologyLibDaoUserDao::getUserChoices' took 0.461ms (1 queries, avg 0.461ms)
repo:365:1
12:28:20,994 Request Failed: error, Internal Server Error
tools.js:60:3
12:28:20,996 default DEBUG DI container setup (cached: yes) (0.371ms)
```

However it works when logged in (as `fossy`)...

In addition, it doesn't seem related to the docker setup as stated in https://lists.linuxfoundation.org/pipermail/fossology-devel/2018-March/002953.html

**Comment by mcjaeger** [comment] 2018-03-06 08:13
it is possible, as discussed on the mailing list, there could be a problem with the session handling that want information from the session that is not available when not logged in.

I think as well this should work.

**Comment by maxhbr** [comment] 2018-03-06 08:23
In the more complex docker-compose setup (in `./install/`) one is able to see the cause in the log:
```
fossology-web_1         | [Tue Mar 06 08:20:46.711207 2018] [:error] [pid 22] [client 172.18.0.1:58204] PHP Fatal error:  Uncaught exception 'Exception' with message 'not allowed without login' in /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:323
Stack trace:
#0 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(240): Fossology\\Lib\\Plugin\\DefaultPlugin->checkPrerequisites()
#1 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(275): Fossology\\Lib\\Plugin\\DefaultPlugin->getResponse()
#2 /usr/local/share/fossology/www/ui/index.php(62): Fossology\\Lib\\Plugin\\DefaultPlugin->execute()
#3 {main}
  thrown in /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php on line 323, referer: http://localhost:8081/repo/?mod=browse
```

**Comment by mhow2** [comment] 2018-03-06 08:33
Yes, sorry, I forgot to mention the error from @maxhbr above. I've been able to see it too with `docker exec 477d12286862 less /var/log/apache2/error.log`

**Comment by maxhbr** [comment] 2018-03-06 09:12
Will be fixed by https://github.com/fossology/fossology/pull/995

**Comment by mhow2** [comment] 2018-03-07 07:53
Thank you. How do I merge this fix into the Docker build as I wait for an official release ?

**Comment by maxhbr** [comment] 2018-03-07 07:59
you might have to check out the branch `maxhbr/fix#994` and build the image from there by hand. Or modify the image and commit it.

Alternatively you could review and test the PR. If it is reviewed it might be merged very soon.

**Comment by mhow2** [comment] 2018-03-07 08:05
Right, but to test the PR I need to build the branch by hand :) Well I'll see what I can do.

**Comment by maxhbr** [comment] 2018-03-07 08:08
You could use the docker-compose setup in `./install` or the vagrant setup. If there is no proxy it should work.

**Closed** 2018-03-07 08:42 UTC
Labels: bug

**Comment by mcjaeger** [comment] 2018-03-07 09:14
hello,

I think if the fix is merged to master, the dockerhub image provides you with the latest build on master:

https://hub.docker.com/r/fossology/fossology/tags/

Kind regards, Michael

**Comment by mhow2** [comment] 2018-03-07 09:26
Thanks, it works :)

However I don't understand why it try to upgrade the db schema every
time the containers are started, as I have persistent data folder for
postgres:

fossy_1         | *** Running postinstall for web-only actions***
fossy_1         | NOTE: using external DB on host fossology-db
fossy_1         | *** update the database and license_ref table ***
fossy_1         | Old release was 3.1.0
fossy_1         |   Applying database functions
fossy_1         | DB schema has been updated for fossology.
fossy_1         | Database schema update completed successfully.

**Comment by mhow2** [comment] 2018-03-07 09:39
I think I tested a bit too much faster.
With the following upload config :
![screenshot-2018-3-7 edit uploaded file permissions](https://user-images.githubusercontent.com/9987241/37084711-872c6de4-21f3-11e8-96b8-436e40b74590.png)

I got a blank page when trying to click the link with that upload name on the browse page. Ie at URI `/repo/?mod=license&upload=3&folder=1&item=109&show=quick`

And again the same error in logs:
`[Wed Mar 07 09:37:46.971314 2018] [:error] [pid 196] [client 172.18.0.1:55528] PHP Fatal error:  Uncaught exception 'Exception' with message 'not allowed without login' in /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:323\nStack trace:\n#0 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(240): Fossology\\Lib\\Plugin\\DefaultPlugin->checkPrerequisites()\n#1 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(275): Fossology\\Lib\\Plugin\\DefaultPlugin->getResponse()\n#2 /usr/local/share/fossology/www/ui/index.php(62): Fossology\\Lib\\Plugin\\DefaultPlugin->execute()\n#3 {main}\n  thrown in /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php on line 323, referer: https://fossology.ow2.org/repo/?mod=browse`
