### ISSUE TITLE
Prevent a user from downloading the source code

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#1304] opened 2019-03-13 11:15 UTC
### Description

In the browser view, an entry in the drop-down list proposes to download the material scanned in a given upload.
The need is to remove the possibility for non-admin users to download this data - although users will still be able to see the files contents by browsing them one by one (or by creating a specific web craweler), the idea is to remove this obvious way to get hold of the whole upload.

#### Steps followed and expected result

A system-wide configuration entry (in Admin -> Customize page) would:
- remove the Download entry from the drop down list
- result in an error if trying to access the download URL directly

We can think of smarter configuration options (for each user, for each upload, etc.), but I suppose a general system-wide option should be enough.
 
#### Screenshots

![image](https://user-images.githubusercontent.com/22956329/54274648-e7e62800-4588-11e9-9bd0-52fdd7ac166c.png)

**Comment by sandipbhuyan** [comment] 2019-03-14 02:13
I want to work on this issue

**Comment by mcjaeger** [comment] 2019-05-20 11:02
@sandipbhuyan pls. feel free to go ahead

**Comment by NicolasToussaint** [comment] 2019-06-20 16:10
Hi @sandipbhuyan,

did you start looking at this issue at all ?
Thanks

**Comment by 360fusion** [comment] 2019-09-18 10:41
@sandipbhuyan, @NicolasToussaint @mcjaeger 

Did anyone get anywhere with this? 

Thanks

**Comment by NicolasToussaint** [comment] 2019-09-18 12:48
@360fusion, we have a very simple patch that removes the 'Download' entry for source code files for non-admin users.
That does not prevent a non-admin user from downloading the source code by guessing and entering the using URL directly though.

I need to re-test, and then I can propose a PR if you want.

**Comment by 360fusion** [comment] 2019-09-18 21:28
Hi,

We managed do some digging and found a similar work around.

Thanks

**Comment by adityabisoi** [comment] 2020-03-09 12:10
I wonder if this issue is already solved? I see that users with `read-write` access are given an option to download the project files. But, the issue description barres all "non-admin" users from doing so.

**Comment by GMishx** [comment] 2020-03-19 11:30
The issue is not solved. Any user with write access will be able to download the files. See
https://github.com/fossology/fossology/blob/b5a389be8ef413fc488b56700ea23bdf3ff9c73a/src/www/ui/ui-download.php#L42

The idea is to allow only admin users and forbid others (as you've mentioned) and make this configurable from "Admin >> Customize".

**Comment by piotreke12** [comment] 2020-04-29 08:55
Hi @360fusion @adityabisoi 

I prepared fix for this problem: #1691 

Administrator will be able to choose which access level will let user download source code (show/hide download button)

Admin > Customize page will have additional option to set:
![image](https://user-images.githubusercontent.com/12530337/80577437-28ac3500-8a07-11ea-93d4-64b84b52bb36.png)

I hope it meets many needs described in this Issue...

**Closed** 2020-06-10 07:55 UTC
Labels: enhancement
