### ISSUE TITLE
Reduce UI yellow path block

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#288] opened 2015-01-09 07:10 UTC
---

Author Name: **Silvano Cirujano Cuesta** 
Original Redmine Issue: 6879, http://www.fossology.org/issues/6879
Original Date: 2014/04/08
Original Assignee: Silvano Cirujano Cuesta

---

Below the top part of the webpages that is persistent all over the UI a yellow block appears in some views. That block shows the path of the file/folder being viewed and the possible views to select from the current view.

!UI_path.png!

The left part showing the path uses
1. one line for the folder,
1. one line for each archiving level (in the shown case one archiving level is the compression with bzip) and
1. the line with the last archiving level shows the path inside of the archive.
Resulting in the shown example in four lines.

Since screens are nowadays much wider than higher and that yellow block is empty to the right of the mentioned paths, presenting all the mentioned path information in one single line would help to optimize the used space.

**Comment by yaobinshi** [comment] 2015-01-09 07:10
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/04/08 16:06:32 +0000

---

You really can't count on a wide window.  There is a lot of variety in how people size their browser and what their viewing device is (like a netbook or a big monitor).  But it would certainly be easy to put the whole path on a single line, and let the browser put in the line breaks if the client browser window isn't wide enough.  I don't see any downsides to doing this.

Do you want to assign yourself the task?

**Comment by yaobinshi** [comment] 2015-01-09 07:10
---

Original Redmine Comment
Author Name: **Silvano Cirujano Cuesta** 
Original Date: 2014/04/11 13:20:34 +0000

---

The attached patch would fix this issue.

View these screenshots for comparison:

Current FOSSology !Yellow_header_original.png!

Modified version !Yellow_header_narrow.png!

**Comment by pguttmann** [comment] 2015-02-04 14:26
Attachments - 1) http://www.fossology.org/attachments/4413/UI_path.png
2) http://www.fossology.org/attachments/4419/fix-backlog-6879.patch
3) http://www.fossology.org/attachments/4425/Yellow_header_narrow.png
4) http://www.fossology.org/attachments/4431/Yellow_header_original.png

**Comment by mcjaeger** [comment] 2018-05-28 11:11
duplicate of https://github.com/fossology/fossology/issues/286

also attachments lost and it is required to rework the yellow area.

**Closed by mcjaeger** 2018-05-28 11:11 UTC
Labels: Category: UI, enhancement
