### ISSUE TITLE
Installation from github clone fails

### ISSUE THREAD

**Issue by vivekaindia** [fossology/fossology#1369] opened 2019-06-03 08:19 UTC
### Description

Installation of fossology fails when tried using the GitHub clone.
But when tried to install fossology using the zip download it works.

### Error Message

```
make[3]: Entering directory '/mnt/c/Users/vivek/Desktop/gsoc/fossology/src/monk/agent'
: not foundsitor: 2: genSquareVisitor:
: not foundsitor: 11: genSquareVisitor:
: not foundsitor: 12: genSquareVisitor: ./squareBuilder
genSquareVisitor: 17: genSquareVisitor: Syntax error: end of file unexpected (expecting "then")
Makefile:63: recipe for target '_squareVisitor.h' failed
make[3]: *** [_squareVisitor.h] Error 2
make[3]: Leaving directory '/mnt/c/Users/vivek/Desktop/gsoc/fossology/src/monk/agent'
Makefile:20: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/mnt/c/Users/vivek/Desktop/gsoc/fossology/src/monk'
Makefile:51: recipe for target 'build-monk' failed
make[1]: *** [build-monk] Error 2
make[1]: Leaving directory '/mnt/c/Users/vivek/Desktop/gsoc/fossology/src'
Makefile:28: recipe for target 'build-src' failed
make: *** [build-src] Error 2
```

#### How to reproduce

* Move to fossology cloned directory
* Run `sudo make install`

#### Screenshots

![error](https://user-images.githubusercontent.com/30703636/58786832-0f87e200-8606-11e9-8e7d-939150a06dfe.PNG)

### Versions

* gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0

#### FOSSology logs

```
2019-05-15 12:53:29 scheduler [2718] :: NOTE: *****************************************************************
2019-05-15 12:53:29 scheduler [2718] :: NOTE: ***                FOSSology scheduler started                ***
2019-05-15 12:53:29 scheduler [2718] :: NOTE: ***        pid:      2719                                     ***
2019-05-15 12:53:29 scheduler [2718] :: NOTE: ***        verbose:  1                                        ***
2019-05-15 12:53:29 scheduler [2718] :: NOTE: ***        config:   /usr/local/etc/fossology                 ***
2019-05-15 12:53:29 scheduler [2718] :: NOTE: *****************************************************************
2019-05-15 12:59:34 scheduler [2718] :: NOTE: *****************************************************************
2019-05-15 12:59:34 scheduler [2718] :: NOTE: ***                FOSSology scheduler closed                 ***
2019-05-15 12:59:34 scheduler [2718] :: NOTE: ***        pid:     2719                                      ***
2019-05-15 12:59:34 scheduler [2718] :: NOTE: *****************************************************************

2019-05-15 12:59:35 scheduler [2900] :: NOTE: *****************************************************************
2019-05-15 12:59:35 scheduler [2900] :: NOTE: ***                FOSSology scheduler started                ***
2019-05-15 12:59:35 scheduler [2900] :: NOTE: ***        pid:      2901                                     ***
2019-05-15 12:59:35 scheduler [2900] :: NOTE: ***        verbose:  1                                        ***
2019-05-15 12:59:35 scheduler [2900] :: NOTE: ***        config:   /usr/local/etc/fossology                 ***
"/var/log/fossology/fossology.log" [readonly] 536L, 54796C
```

**Comment by vivekaindia** [comment] 2019-06-03 09:15
## Error Re-appeared
* Clean old fossology
* Clean Make
* Install from the fossology clone. (As a new install)

### Error 1: During the installation of dependencies

* from clone source
* `sudo utils/fo-installdeps`

#### Error message

```
utils/fo-installdeps: line 24: $'\r': command not found
utils/fo-installdeps: line 25: syntax error near unexpected token `$'{\r''
'tils/fo-installdeps: line 25: `show_help() {
```

### Error 2: During the execution of make

* from clone source
* `make`

#### Error message

```
make[3]: Entering directory '/mnt/c/Users/vivek/Desktop/gsoc/fossology/src/monk/agent'
: not foundsitor: 2: genSquareVisitor:
: not foundsitor: 11: genSquareVisitor:
: not foundsitor: 12: genSquareVisitor: ./squareBuilder
genSquareVisitor: 17: genSquareVisitor: Syntax error: end of file unexpected (expecting "then")
Makefile:63: recipe for target '_squareVisitor.h' failed
make[3]: *** [_squareVisitor.h] Error 2
make[3]: Leaving directory '/mnt/c/Users/vivek/Desktop/gsoc/fossology/src/monk/agent'
Makefile:20: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/mnt/c/Users/vivek/Desktop/gsoc/fossology/src/monk'
Makefile:51: recipe for target 'build-monk' failed
make[1]: *** [build-monk] Error 2
make[1]: Leaving directory '/mnt/c/Users/vivek/Desktop/gsoc/fossology/src'
Makefile:28: recipe for target 'build-src' failed
make: *** [build-src] Error 2
```

**Comment by GMishx** [comment] 2019-06-03 09:24
This appears to be an issue with line breaks of Unix on a DOS system. Try converting the line breaks from `CRLF` to `LF`. Try using `dos2unix` command.

**Comment by vivekaindia** [comment] 2019-06-03 09:51
> This appears to be an issue with line breaks of Unix on a DOS system. Try converting the line breaks from `CRLF` to `LF`. Try using `dos2unix` command.

This was very much useful and it worked for me.

**Comment by GMishx** [comment] 2019-06-03 10:10
Are you using WSL? Does fossology works on it?

If the issue is resolved, kindly consider closing the issue.

**Comment by vivekaindia** [comment] 2019-06-03 12:11
I work fine now...

* It's important to clone the repository using `terminals`, rather than `git bash` and `GitHub desktop`

**Closed** 2019-06-03 12:11 UTC
Labels: Category: Build/install/config, Category: Package Install, bug
