### ISSUE TITLE
Upload from File page cannot select folder

### ISSUE THREAD

**Issue by larainema** [fossology/fossology#400] opened 2015-03-13 05:35 UTC
![image](https://cloud.githubusercontent.com/assets/5294029/6633563/7a902c0c-c985-11e4-8b6e-28a609bd8fa5.png)

**Comment by yaobinshi** [comment] 2015-05-25 06:45
I did the testing with lasted code, works fine.

**Comment by bobgob** [comment] 2015-05-26 20:21
I just closed #443 as a duplicate of this issue that I filed.   I could reproduce the same issue as @larainema 
From #443 :
> Testing current master 420e4c9
>Upload from File "Select the folder for storing the uploaded file:" pulldown only shows my root folder. It should show my subfolders as well.

**Comment by bobgob** [comment] 2015-06-01 16:14
I just applied d81792 and now I see that Upload from URL has the same bug.

**Comment by steffen-weber** [comment] 2015-06-29 16:55
This was probably caused by using the old FolderDao without migration of column folder.parent_fk for 2.4 data. The newer FolderDao from https://github.com/fossology/fossology/pull/462 shouldn't have this migration issue. Can you re-test it @larainema?

**Comment by bobgob** [comment] 2015-07-24 20:35
Tested on #abb949f
Closing.

**Closed by bobgob** 2015-07-24 20:35 UTC
Labels: bug, Category: UI, Priority: High
