### ISSUE TITLE
a read only user can find  none public files 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#339] opened 2015-01-09 08:29 UTC
---

Author Name: **larry shi** 
Original Redmine Issue: 7569, http://www.fossology.org/issues/7569
Original Date: 2014/08/28
Original Assignee: larry shi

---

a read only user can find  none public files 

we should confirm if Search function has the permission control or not.

**Comment by mcjaeger** [comment] 2015-08-18 16:17
please, would it be possible to clarify what "none public files" are exactly?

The bug that I am seeing is that even a upload was made public, a user cannot see this upload if he not member of the group that was set when uploading. So "visible to all groups" at file upload does not seem to have the anticipated effect.

**Comment by bobgob** [comment] 2015-08-18 16:43
On #25f4d65, I can't reproduce this.  
Test case:
As user A: upload file, set "Make Public"
Login as  user B (not in original uploaders group)
Result: B can see upload A

**Comment by mcjaeger** [comment] 2015-09-16 12:23
confirmed, closing

**Comment by mcjaeger** [comment] 2015-09-16 12:23
confirmed closing

**Closed by mcjaeger** 2015-09-16 12:23 UTC
Labels: bug, Category: UI, Priority: High
