### ISSUE TITLE
Scheduler Administration usability

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#41] opened 2015-01-08 06:33 UTC
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 447, http://www.fossology.org/issues/447
Original Date: 2012/01/13
Original Assignee: Mary Laser

---

Scheduler Administration has some usability issues.  These are a combination of UI issues and data not coming from the scheduler.

For example, rather than pause job 687, I should be able to pause "mytar.tar nomos (job 687)"

Also, you should only be able to pause a job, change priority, shutdown the scheduler, etc., if you have the right permission level.

There is no way to kill a job.

Job status could be formatted much better

JOB_COMPLETE, JOB_CHECKEDOUT, etc., are not explained

Some operation result in empty secondary pulldowns.  For example, if you unpause a job and there are no jobs to unpause.  The user can then hit submit on this.  The user should just be told that there are no jobs to unpause.

Display fossology.conf should be an option.

**Comment by yaobinshi** [comment] 2015-01-08 06:33
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:01 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment] 2017-03-13 11:20
it is not a bug, some issue are solved by today, closing because of missing pickup

**Closed by mcjaeger** 2017-03-13 11:20 UTC
Labels: bug, Category: UI, Priority: Normal, Status: New, Tracker: Bug
