### ISSUE TITLE
REST API: Upload filter in the api

### ISSUE THREAD

**Issue by Shruti3004** [fossology/fossology#2032] opened 2021-06-25 04:04 UTC
### Description

At present, we are having pagination system in the upload api but since in the current implementation of Browse page we are having search filter on each of the category, if user search for any file and if that file doesn't exist on that page index then we are not able to deliver the correct data, or we have to make the request for all the files which in return increase the load on server.

**Comment by GMishx** [comment] 2021-06-28 11:04
Duplicate of #2007

Closing here.

**Closed by GMishx** 2021-06-28 11:04 UTC
Labels: enhancement
