### ISSUE TITLE
'Clean Text' button click does not clean texts with character, '*'

### ISSUE THREAD

**Issue by rahulmohang** [fossology/fossology#2100] opened 2021-09-19 00:41 UTC
### Description

The action on 'Clean Text' button does not remove the character, '*', that is very common  part of texts. 

#### How to reproduce

1. Go to Bulk recognition on a file with a license text starting with the '*' character.
2. Paste the reference text to the 'Reference text' field. 
3. Click the 'Clean Text' button. 

### Versions

* Last commit id on master: Commit: [#33f5b5] 2020/11/30 06:11 UTC
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### FOSSology logs

Logs generated under /var/log/fossology/fossology.log

#### Apache logs

Logs generated under /var/log/apache2/error.log

#### Job logs

Logs generated under Geeky Scan Details (Job history => click on agent's job id)

**Comment by GMishx** [comment] 2021-10-01 07:41
I though I replied already but there is a PR with more comment identifiers
https://github.com/fossology/fossology/pull/2073

**Comment by rahulmohang** [comment] 2021-10-01 08:27
ok, thank you. One comment though - Most of the characters are cleaned as of now. As per what I observed, '*' is not.

**Comment by GMishx** [comment] 2021-10-01 08:45
Yeah, the PR adds following new symbols to the mix
- `dnl`
- `,`
- `*`
- `'''`
- `"""`

Also, ability to provide your own list per scan.

**Comment by rahulmohang** [comment] 2021-10-02 03:43
Thank you.

**Comment by teekhandekar** [comment] 2022-03-19 15:16
@GMishx can I work on this ?

**Comment by GMishx** [comment] 2022-03-28 05:50
@rahulmohang , can you please check if the issue is resolved or still exists?

**Comment by rahulmohang** [comment] 2022-03-28 06:31
@GMishx , Yes.

**Comment by rahulmohang** [comment] 2022-03-28 06:32
I will check.

**Comment by rahulmohang** [comment] 2022-04-13 08:15
@GMishx , it is working. Thank you. Please excuse me for the late response. We took some time to set up the new version of Fossology.

**Comment by GMishx** [comment] 2022-04-13 13:15
Thanks for confirmation @rahulmohang ,closing the issue.

**Closed** 2022-04-13 13:15 UTC
