### ISSUE TITLE
How to Handle JAR Files in Java Projects?

### ISSUE THREAD

**Issue by chilloutman** [fossology/fossology#955] opened 2017-12-05 17:25 UTC
Is there a way to do a "Clearing Decision" recursively? To word if differently, can I set the identified license for a JAR archive _and_ all files unter it?

For example: I upload a WAR file, which in turn has several JAR files. I don't have to look at every file inside every JAR archive. Can I mark identify a license for `libs/dependency.jar`, and all files in it `libs/dependency.jar/**` with a _single_ action?

(In #239, it was proposed that FOSSology should download dependencies from the repositories. An easier alternative could be to upload the built artefact (e.g. WAR), which already contains all the dependencies. The issue of how to classify JAR files still applies.)

**Comment by mcjaeger** [comment] 2017-12-13 09:05
yes, you can. click on "[Edit]":
![image](https://user-images.githubusercontent.com/3418977/33930336-d5b566da-dfec-11e7-9b77-80d00ebff7a1.png)
And then choose a license that you would like, for example concluding "AFL-1.1":
![image](https://user-images.githubusercontent.com/3418977/33930405-15534334-dfed-11e7-8b71-3b8022f27f81.png)

**Comment by chilloutman** [comment] 2017-12-14 15:44
Thanks.

Can the conclusion also be done in bulk?

I've tried adding a License for a JAR file, which works fine. I then just close the popup? The "Edited Results" and the "Files Cleared" columns remain unchanged. Am I missing something?

**Comment by woznik** [comment] 2018-04-11 12:54
Hello Michael
I would like to point out the same issue.
I need exactly the same functionality. Assign/Conclude one license to entire jar (or dierectory) recursively.
The case is that in the jar file I see scanner license indicating many different licences. When I do the Edit and select a specific license (BSD) the changes are made only to the files with "no_license_found".

Second wired behavior of edit is:
When I do the edit option on a folder (or jar) 
![image](https://user-images.githubusercontent.com/17202024/38617258-ca5436b0-3d96-11e8-80d7-e0863ab2c442.png)

and mark all licenses in the left panel 

![image](https://user-images.githubusercontent.com/17202024/38617196-9d85a768-3d96-11e8-8216-b836b24c1cf3.png)

to be removed:

![image](https://user-images.githubusercontent.com/17202024/38617279-e1c6b5fc-3d96-11e8-9955-9c2a34186616.png)

after this action the licenses marked to be removed are added as concluded:

![image](https://user-images.githubusercontent.com/17202024/38617710-01c76030-3d98-11e8-85a7-267246e0b99a.png)

Isn't it an odd behavior?

How could I select only one license for entire folder?

Paweł Woźnicki

**Comment by mcjaeger** [comment] 2019-02-15 22:39
seems to be duplicate of https://github.com/fossology/fossology/issues/456

**Closed by mcjaeger** 2019-02-15 22:39 UTC
Labels: needs clarification, question
