### ISSUE TITLE
Wget command not working in web api

### ISSUE THREAD

**Issue by TheInvoker** [fossology/fossology#881] opened 2017-07-22 01:44 UTC
I want to use the wget command to submit a file to the service and get the results. I tried the command from here

http://archive15.fossology.org/projects/fossology/wiki/Using_FOSSology_from_the_Command_Line

`wget -qO - --post-file myfile.c http://myfossologyserver/?mod=agent_nomos_once`

But all it does is just output the html of the http link. It does not output the license information like in the example in that link.

Does anyone know what is wrong?

Thanks

**Comment by maximilianhuber** [comment] 2017-07-23 15:23
duplicate of #880.

Your problem might be that the one-shot-nomos now needs authentication.

**Comment by maximilianhuber** [comment] 2017-07-23 15:40
See discussion at #880 for a possible solution.

**Closed by maximilianhuber** 2017-07-23 15:40 UTC
Labels: duplicate, question
