### ISSUE TITLE
Standalone Docker container fails due to missing priveledges

### ISSUE THREAD

**Issue by maximilianhuber** [fossology/fossology#723] opened 2016-12-06 07:59 UTC
In the `docker-entrypoint.sh` script is the line https://github.com/fossology/fossology/commit/c8b4b5485064a7681ea6681f1c8c2c8bf24c5279#diff-60713fb19f6c50a2473835df63ff17f9R52 which starts the postgresql-db for the standalone container.

Since this script is due to recent changes called (#720) with an unprivileged user, which is not allowed to start the db service, it fails.

--

this bug was discovered by Manfred Wilner and posted on the dev-mailing-list:
> I followed direction for docker on Ubuntu and was able to pull down the image but:
> ```
> Digest: sha256:5103804e8decb33f8bf1ac13dea7757648e3b752800a915784170f8af4eceb7a
> Status: Downloaded newer image for fossology/fossology:latest
> *****************************************************
> WARNING: No database host was set and therefore the
> internal database without persistency will be used.
> THIS IS NOT RECOMENDED FOR PRODUCTIVE USE!
> *****************************************************
> chmod: changing permissions of '/var/run/postgresql': Operation not permitted
> ```

**Comment by maximilianhuber** [comment] 2016-12-06 11:08
Maybe the following changes might help:
```diff
diff --git Dockerfile Dockerfile
index a30564c..4e71dbe 100644
--- Dockerfile
+++ Dockerfile
@@ -82,6 +82,5 @@ EXPOSE 8081
 
 ################################################################################
 VOLUME /srv/fossology/repository/
-USER fossy
 
 ENTRYPOINT ["/fossology/docker-entrypoint.sh"]
diff --git install/docker-compose.base.yml install/docker-compose.base.yml
index b96e015..f97ebd6 100644
--- install/docker-compose.base.yml
+++ install/docker-compose.base.yml
@@ -24,3 +24,4 @@ services:
       - FOSSOLOGY_DB_HOST=fossology-db
       - FOSSOLOGY_DB_NAME=fossology
       - FOSSOLOGY_DB_USER=fossy
+    user: fossy
```

**Comment by bufferoverflow** [comment] 2016-12-06 20:59
the problem is fo-postinstall.sh (needed for initialize the database) need root to start.
possible solutions:
* Skip root validation if there is only database initialization
* do the rest of initializations while building docker image (as root)

**Comment by florianwittmann** [comment] 2017-02-09 12:26
I have the same problem and also getting the
`chmod: changing permissions of '/var/run/postgresql': Operation not permitted`
with the standalone docker image without external postgres.

**Comment by maximilianhuber** [comment] 2017-03-08 15:45
@bufferoverflow the output you have seen is the regular output. That is no error.

**Comment by max-wittig** [comment] 2017-03-10 14:24
This was fixed in https://github.com/fossology/fossology/commit/8c1fcd3a8b1e81ac16e78c5c61c287ca88ed837b

**Closed by max-wittig** 2017-03-10 14:24 UTC
