### ISSUE TITLE
SPDX output missing files

### ISSUE THREAD

**Issue by kestewart** [fossology/fossology#792] opened 2017-04-06 15:40 UTC
Its been recently noticed by comparing the output of FOSSology with other tools, that files without licenses are missing from SPDX documents.

The SPDX format expects that all files in a package will be in the document.  (see: [](https://spdx.org/spdx-specification-21-web-version#h.nmf14n) first sentance)

Could this please be fixed before the 3.1 release, as one of the highlights of the release is the generation of tag:value - and the missing files are going to be pretty visible once serious analysis happens.

**Comment by maximilianhuber** [comment] 2017-04-08 17:34
A solution might be something like
```diff
diff --git a/src/spdx2/agent/spdx2.php b/src/spdx2/agent/spdx2.php
index f90f0b34b..36133a5dc 100644
--- a/src/spdx2/agent/spdx2.php
+++ b/src/spdx2/agent/spdx2.php
@@ -287,6 +287,11 @@ class SpdxTwoAgent extends Agent
     $clearingDecisions = $this->clearingDao->getFileClearingsFolder($itemTreeBounds, $this->groupId);
 
     $filesWithLicenses = array();
+    $items = $this->uploadDao->getContainedItems($itemTreeBounds);
+    foreach ($items as $item) {
+        $filesWithLicenses[$item->getFileId()] = [];
+    }
+
     $clearingsProceeded = 0;
     foreach ($clearingDecisions as $clearingDecision)
     {
```
although this is not yet working since it uses the wrong IDs.

**Comment by mcjaeger** [comment] 2017-04-13 08:31
it should be noted that it is about file without scanner findings or (logical) license conclusions, just to clarify "files without licenses are missing from SPDX".

**Comment by pguttmann** [comment] 2017-04-13 11:55
One more related observation/comment on this issue is the reporting of non-spdx listed licenses, such as GNU-Manpages, IOS and GFDL. None of which appear in https://spdx.org/licenses/
But are reported when analyzing: http://xmlsoft.org/sources/libxml2-2.7.7.tar.gz

**Comment by shaheemazmalmmd** [comment] 2017-04-14 08:53
The output for the files with no_license_found should be like below ?

> FileName: zlib-1.2.8/examples/README.examples
> SPDXID: SPDXRef-item23
> FileChecksum: SHA1: f793f7b378233d7e644754e603695966487576b5
> FileChecksum: MD5: 7d040e322c50440b203bd70b3a448470
> LicenseConcluded: NOASSERTION
> LicenseInfoInFile: NOASSERTION
> FileCopyrightText: NONE

**Comment by mcjaeger** [comment] 2017-04-14 12:13
@pguttmann I need some help here, as I am not getting what the issue is: could you pls help us with describing what you observe and what would you think should be observed?

**Comment by kestewart** [comment] 2017-04-14 17:49
@shaheemazmalmmd 
That's fine.     Also another way of expressing it might be:
FileName: zlib-1.2.8/examples/README.examples
SPDXID: SPDXRef-item23
FileChecksum: SHA1: f793f7b378233d7e644754e603695966487576b5
FileChecksum: MD5: 7d040e322c50440b203bd70b3a448470
LicenseConcluded: NOASSERTION
LicenseInfoInFile: NONE
FileCopyrightText: NONE

For LicenseInfoInFIle - as nothing was detected,   NONE may be more appropriate,  but NOASSERTION is ok.

**Comment by mcjaeger** [comment] 2017-05-22 11:32
closed by: https://github.com/fossology/fossology/pull/803

**Closed by mcjaeger** 2017-05-22 11:32 UTC
